### ISSUE TITLE
Possible loss of `data` in `transition_impl`

### ISSUE THREAD

**Issue by StoneCypher** [StoneCypher/fsl#1259]
The claim is made that the transition_impl path can drop data from current state and history if hooks are not in use

There is a partial reproduction in StoneCypher/jssm#557

Thanks to @WNemencha for reporting this originally

**Comment by StoneCypher** [comment]
Confirmed

![image](https://github.com/StoneCypher/fsl/assets/77482/ce66579e-22f5-4fa1-bac3-630924f195a6)

**Comment by StoneCypher** [comment]
`data` argument for `transition`, `action`, `go`, `do` via `transition_impl` wasn't actually wired up.  it looked like it was, because the data return value from hooks was and they go through the same mutual implementor.

You were right that [the call pattern had to be implemented without hooks](https://github.com/StoneCypher/jssm/blob/main/src/ts/jssm.ts#L2378-L2380), but I [also had to implement the call pattern with hooks](https://github.com/StoneCypher/jssm/blob/main/src/ts/jssm.ts#L2357-L2361).

This led to noticing that at this time, there is also [no way practical way to set `data` to `undefined`](https://github.com/StoneCypher/fsl/issues/1264), which will be fixed promptly.

[26 tests added to enforce](https://github.com/StoneCypher/jssm/blob/main/src/ts/tests/data.spec.ts#L10-L238):

1. a common sense full cycle without hooks
2. a common sense full cycle with hooks
3. every adjacent pairing of hooks in ordering, to assert that hooks override in the correct order

Thank you, @WNemencha , for improving this state machine.  I apologize for this oversight.  

![image](https://github.com/StoneCypher/jssm/assets/77482/979ce015-534e-46ec-9995-e1bfeedb7dee)

**Comment by WNemencha** [comment]
You're welcome, thanks for fixing this.
