### ISSUE TITLE
Where is the source code for the live editor?

### ISSUE THREAD

**Issue by lborgman** [StoneCypher/fsl#1301]
This format should give a rough basis for how to report bugs in JSSM.  Remove a section if it doesn't make sense.

**Describe the bug**
Can't find the source in the repo.

**To Reproduce**
Searched for the html file.

**Expected behavior**
Expected a hit.

**Additional context**
Github

**Comment by StoneCypher** [comment]
There are several of them, but, probably here: https://github.com/StoneCypher/jssm-viz-demo

**Comment by StoneCypher** [comment]
cool to close this?
