### ISSUE TITLE
Remove the cutesy unicode operators

### ISSUE THREAD

**Issue by StoneCypher** [StoneCypher/fsl#145]
It's brutally difficult to find font support, nobody cares, I don't use it, &c.

**Comment by machinshin** [comment]
wait, so you made operators for the unicode of ~> <~ and -> and so forth? :) 

where is that in the spec, that's hilarious :) 

but yes, all the peoople of the world got together in the the 1990's and decided APL and it's kin are mostly horrible :)

**Comment by machinshin** [comment]
@StoneCypher : more details needed on this.

**Comment by StoneCypher** [comment]
i don't know what details you want on this

**Comment by StoneCypher** [comment]
eh i'm leaving them

they aren't hurting anything, they just mean some extra test cases
