### ISSUE TITLE
make a .d.ts

### ISSUE THREAD

**Issue by StoneCypher** [StoneCypher/fsl#151]
https://github.com/Microsoft/dts-gen

**Comment by machinshin** [comment]
needs deets

**Comment by StoneCypher** [comment]
i don't know what details you want

**Comment by StoneCypher** [comment]
related to #152 (maybe obviates it)

got help from ts gitter @ fatcerberus 

i asked about the problem wherein module is for es6 and main for es5, and how does one expose typescript; bruce suggests that a compiler generated `.d.ts` is as good as hand written, and all one needs.  he also suggests that `Definitely Typed` is for people adding types to repos outside their control, and that a repo under the author's control is better off containing the types internally.

soooooo, the next step is to get a `.d.ts` out of the compiler

**Comment by StoneCypher** [comment]
Addresses StoneCypher/jssm#392

**Comment by StoneCypher** [comment]
Probably easier with #383
