### ISSUE TITLE
Add "add headers" button to make it easier to re-add headers

### ISSUE THREAD

**Issue by StoneCypher** [StoneCypher/fsl#175]

**Comment by machinshin** [comment]
@StoneCypher this also seems to exist already?

**Comment by StoneCypher** [comment]
Oh, indeed it does.  Thanks, @machinshin 

Do you want to do the tooltip?  If not I will.  (You can just open PRs like that, no need to discuss it.)

**Comment by machinshin** [comment]
@StoneCypher I'll take it,  easy enough.
