### ISSUE TITLE
fsl organization

### ISSUE THREAD

**Issue by machinshin** [StoneCypher/fsl#208]
we should create a GitHub organization for fsl and move all the related repositories into it. 

Note: this can be a pain in the ass cause it has to be done in stages or it could end up breaking all kinds of things

**Comment by StoneCypher** [comment]
you've had an outstanding invitation to it for a month now 🤣

https://github.com/fsl-lang

**Comment by StoneCypher** [comment]
I'll leave this issue open until you've joined

Please close this issue once you join the org

**Comment by machinshin** [comment]
@StoneCypher 

closing now, but here's a link on how to move repos to an org

https://help.github.com/en/articles/transferring-a-repository
