### ISSUE TITLE
Unroll old JSSM folded issue list

### ISSUE THREAD

**Issue by StoneCypher** [StoneCypher/fsl#25]

**Comment by StoneCypher** [comment]
https://github.com/StoneCypher/jssm/issues/329

**Comment by machinshin** [comment]
@StoneCypher : what is needed to close this?

**Comment by StoneCypher** [comment]
i have to go through the old list and make sure they all got migrated

**Comment by StoneCypher** [comment]
Also unrolled StoneCypher/jssm#330 in the process

@machinshin - complete.  Produced around 40 issues in the process
