### ISSUE TITLE
Issue Trees

### ISSUE THREAD

**Issue by StoneCypher** [StoneCypher/fsl#45]
![image](https://user-images.githubusercontent.com/77482/50403296-4eaa3100-0752-11e9-96ee-8b14f4a4413b.png)

https://en.wikipedia.org/wiki/Issue_tree#/media/File:An_issue_tree_showing_how_a_company_can_increase_profitability.png

**Comment by machinshin** [comment]
Not much to do here in india, so here's the fsl code (attached)
1. where (and in what repo) do you want this example file uploaded?

2. there are couple of inconsistencies between the png & the code
  i. the png shows some words in colored-bold, is that possible in fsl?  if not, how hard would it be to add (maybe some kind of embedded markdown?)?
  ii. how/can do i put a box around a set of items?
  iii. should be possible to define the rendered png orientation? 
3. found 2 things i'd like to make writing fsl easier (at least in the live editor)
  i. in the fsl code it's hard to track levels ( i manually added L# in the comments)
  ii. I wish I could've used variables, cause atm all the strings make it hard to track. I believe that's in the roadmap, neh? 

[tree.txt](https://github.com/StoneCypher/fsl/files/4063949/tree.txt)

**Comment by StoneCypher** [comment]
This is awesome.  Thank you

You deserve contributor credit for this.  Open a PR putting it here: https://github.com/StoneCypher/jssm/tree/master/src/machines

**Comment by StoneCypher** [comment]
@machinshin - you didn't open the pr, you just merged to your fork

**Comment by machinshin** [comment]
@StoneCypher : it merged the commit to my fork, then created this PR: https://github.com/StoneCypher/jssm/pull/393
but github makes those two actions equivalent >:( . please merge that PR and let's close this one out.

**Comment by StoneCypher** [comment]
Oh heck, I was looking at the wrong thing :)
