### ISSUE TITLE
fsl.tools viewer is out of date, crashing on valid fsl

### ISSUE THREAD

**Issue by StoneCypher** [StoneCypher/fsl#460]
so like

the fsl.tools viewer has a version from three or four minors back, that doesn't do colors or shapes

and the editor's default code has colors and shapes now, so, unless you know to take that out, that looks broken

ffffiiiiiiixxxxxx iiiiiiiiiittttt

![](https://media1.tenor.com/images/61fa1ea6eecc1c69c2a5a6c45827717d/tenor.gif?itemid=9239202)

**Comment by StoneCypher** [comment]
@machinshin When you write "closes X" and merge them into your fork, they close the base issue

**Comment by machinshin** [comment]
@StoneCypher : that's stupid, it should only close the issue when the PR is merged into upstream..
this makes "closes X" almost useless >:(

**Comment by StoneCypher** [comment]
How else can it work across repos

You put that in the PR comment at the merge for the main repo instead of the fork

**Comment by StoneCypher** [comment]
So I manually updated this again the other day, and I'm going to close this on that account

But I also want to point out that automated updates are on the horizon and might go in today.  I've been working on them for a week or so now, and will look at them in #863
