### ISSUE TITLE
Comedy flowcharts

### ISSUE THREAD

**Issue by StoneCypher** [StoneCypher/fsl#48]
Sometimes it's an improvement.  Usually it isn't.

**Comment by StoneCypher** [comment]
![image](https://user-images.githubusercontent.com/77482/50404063-a2b81400-0758-11e9-9e80-c6f464ee1111.png)

**Comment by StoneCypher** [comment]
![image](https://user-images.githubusercontent.com/77482/50404071-ac417c00-0758-11e9-8f1d-20c9f5108b60.png)

**Comment by machinshin** [comment]
@StoneCypher : these are example machines I presume?

**Comment by StoneCypher** [comment]
they're reminding me how to make examples people would read

**Comment by StoneCypher** [comment]
ya it was a bad idea for me to put more than one image in a single thread though

**Comment by StoneCypher** [comment]
It's good work.  However, graphviz is an idiot.  I'd like to request a few very small cosmetic changes

1. If you put newlines as `\n` into the labels, those rectangles won't be brutally wide
1. Graphviz makes bad choices about sizing circles.  Honestly, except for 1/2 word lines, graphviz is bad at sizing things that aren't rectangle, record, Mrecord, component, and cylinder
1. Once those labels are sizing differently, consider playing with `flow: right;` and the other three directions to find what you prefer

![image](https://user-images.githubusercontent.com/77482/113914760-bf927d00-9792-11eb-98e1-4fbdf312d2e6.png)
