### ISSUE TITLE
Errors not being propagated upwards into editor

### ISSUE THREAD

**Issue by StoneCypher** [StoneCypher/fsl#532]
The reason #531 required Christopher to reach out to me is that the engine was saying `Uncaught Error: already has "a" to "b"`, but the editor wasn't catching it

As a result, Christopher couldn't tell what was actually wrong

Fix this

**Comment by blackeuler** [comment]
Hmm I wasn't sure if not propagating the error was a design choice, users shouldn't be concerned with Console Errors. This did make it at least seem like on the surface an intended feature instead of a crash.

**Comment by StoneCypher** [comment]
it's not a console error. the machine is `throw`ing because the code is wrong (by design)

the editor absolutely should be picking it up

![image](https://user-images.githubusercontent.com/77482/104824536-6821e800-5807-11eb-9a40-fafab8edfcb3.png)

**Comment by StoneCypher** [comment]
Re-check this while you're at it

https://github.com/StoneCypher/fsl/issues/343
