### ISSUE TITLE
The Punjabi Name Theory

### ISSUE THREAD

**Issue by machinshin** [StoneCypher/fsl#607]
Found on Facebook, I love this

Also a good example of bi-directional list spread

https://scontent-sjc3-1.xx.fbcdn.net/v/t1.6435-9/174212005_1417799495242229_4762831337818819635_n.jpg?_nc_cat=103&ccb=1-3&_nc_sid=825194&_nc_ohc=HOj8yuZQ6_4AX_4hvbq&_nc_ht=scontent-sjc3-1.xx&oh=d8ef3a0c8ded3077ba9227682a80411f&oe=60A39386

**Comment by StoneCypher** [comment]
i can count 29 people i've known through this list.  that's a real number
