### ISSUE TITLE
May a next hook abuse the edge graph?

### ISSUE THREAD

**Issue by StoneCypher** [StoneCypher/fsl#954]
@patrickkennedy raises an interesting issue.  What happens if a hook wants to follow an edge that isn't described in the edge graph?

Defacto I had been presuming they could just do whatever, and had been writing machines missing edges and just sort of expecting the hook behavior to fill in conceptually, like so:

```typescript
const vending_machine = jssm.from(`

  wait 'nickel'  -> add_nickel;
  wait 'dime'    -> add_dime;
  wait 'quarter' -> add_quarter;

  wait 'vend' -> try_vend;

`, { paid_cents: 0 });

vending_machine.hook_entry('add_nickel', ({data}) => {
  return { pass: true, next: 'wait', data: { paid_cents: data.paid_cents + 5 } }; 
});

vending_machine.hook_entry('dispense', ({data}) => {
  // physically dispense product somehow
  return { pass: true, next: 'wait' }; 
});

vending_machine.hook_entry('vend', ({data}) => {
  if (data.paid_cents > 75) {
    return { pass: true, next: 'dispense', data: { paid_cents: data.paid_cents - 75 } }; 
  } else {
    return { pass: true, next: 'wait', data: { paid_cents: data.paid_cents, no_vend_light: true } }; 
  }
});

// etc
```

That breaks the rendering and a lot of the safety, though

We could rely on disabling forced edges from the outside #953, and then hold those as forced edges, and then the knot ties itself:

```typescript
const vending_machine = jssm.from(`

  -call_forced_edges: disabled;

  wait 'nickel'  -> add_nickel  ~> wait;
  wait 'dime'    -> add_dime    ~> wait;
  wait 'quarter' -> add_quarter ~> wait;

  wait 'vend' -> try_vend ~> [dispense wait];
  dispense ~> wait;

`, { paid_cents: 0 });

vending_machine.hook_entry('add_nickel', ({data}) => {
  return { pass: true, next: 'wait', data: { paid_cents: data.paid_cents + 5 } }; 
});

vending_machine.hook_entry('dispense', ({data}) => {
  // physically dispense product somehow
  return { pass: true, next: 'wait' }; 
});

vending_machine.hook_entry('vend', ({data}) => {
  if (data.paid_cents > 75) {
    return { pass: true, next: 'dispense', data: { paid_cents: data.paid_cents - 75 } }; 
  } else {
    return { pass: true, next: 'wait', data: { paid_cents: data.paid_cents, no_vend_light: true } }; 
  }
});
```

Mostly, I'm with him: this is a good requirement to make.  Having hook transitions within the graph, in general, is a smart move.

***Except*** when there's a hundred states and the transitions are programmatic.  We don't want to have to expect to write out every one of those that's possible, and discover missing ones the hard way 😥  

&nbsp;

# Outcome

So we need to create an attribute `-hooks-within-graph: boolean;`, default true, where if the hooks are within the graph, they can't call an undescribed edge, but if someone has gone to the trouble of making that false, the protection is declined for that machine.

**Comment by PatrickKennedy** [comment]
I guess my main question is what's the benefit of using forced edges here?

There's a couple things I'm not super clear on, but it seems like the functional benefit of forced transitions is an added level of safety to require making the transition explicit through the `force_transition` function. #953 extends that and makes them completely invisible to the outside? So combining it here would serve to make the forced edge as more of an explicit note to the graph?

Is there a downside to documenting it with a normal edge?

**Comment by StoneCypher** [comment]
> I guess my main question is what's the benefit of using forced edges here?

You don't have to.  That's just if you only want the hooks to be able to follow those edges, rather than some outside user, and then only in combination with the attribute.

&nbsp;

> Is there a downside to documenting it with a normal edge?

Nope

**Comment by StoneCypher** [comment]
In retrospect, no, Patrick is right, just make it a normal edge, and disallow hooks calling edges that don't exist

That is the machine as it is and is enforced today

This is purposeless cruft
